//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hasznaltruha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruha
    {
        public int id { get; set; }
        public int fk_tipus_id { get; set; }
        public string szin { get; set; }
        public string meret { get; set; }
        public decimal ar { get; set; }
    
        public virtual Tipus Tipus { get; set; }
    }
}
